### ISSUE TITLE
Recipe App Kanban Board Setup

### ISSUE THREAD

**Issue by Adams-Ghub** [tomdan-ai/Recipe-App#12]
We are a group of two members just as follows

- Student A = @tomdan-ai 
- Student B = @Adams-Ghub 
[Kanban board link](https://github.com/users/tomdan-ai/projects/4)

**Comment by Davidosky007** [comment]
Hi @Adams-Ghub @tomdan-ai 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the correct link to the Kanban board Kindly add the correct one 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Ibizugbe** [comment]
Hi @Team👋🏼👋🏼👋🏼, 

![approved](https://github.com/tomdan-ai/Recipe-App/assets/64643995/4752a70d-237d-4598-bb75-6072cb0478a9)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] The project board contains the required columns👍🏼.
- [x] Provisions has been made for every project requirements👍🏼.
- [x] Points are fairly distributed👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
